image: 'node:latest'
services:
  - 'redis:latest'
  - 'postgres:latest'
cache:
  paths:
    - node_modules/
test:
  script:
    - npm install
    - npm run test
deploy:
  stage: deploy
  environment:
    name: production
    url: null
  script:
    - cd /var/www/nodejs-starter/app
    - git fetch origin
    - git checkout master
    - npm install --production
    - pm2 restart ecosystem.config.js
  tags:
    - nodejs
  only:
    - master
